annotations: []
smart_annotations:
  - tag: VLAN-10
    is_on: true
    padding: 35
    label: VLAN-10
    tag_offset_x: 0
    tag_offset_y: 0
    tag_size: 14
    group_distance: 400
    thickness: 1
    border_style: ''
    fill_color: '#A95FBE80'
    border_color: '#00000080'
    z_index: 1
  - tag: VLAN-20
    is_on: true
    padding: 35
    label: VLAN-20
    tag_offset_x: 0
    tag_offset_y: 0
    tag_size: 14
    group_distance: 400
    thickness: 1
    border_style: ''
    fill_color: '#D5006D80'
    border_color: '#00000080'
    z_index: 2
nodes:
  - boot_disk_size: null
    configuration:
      - name: ios_config.txt
        content: |2-

          hostname R1

          interface GigabitEthernet0/0
           no ip address
           duplex auto
           speed auto
           media-type rj45
    cpu_limit: 100
    cpus: null
    data_volume: null
    hide_links: false
    id: n0
    image_definition: null
    label: R1
    node_definition: iosv
    parameters: {}
    ram: 512
    tags: []
    x: 960
    y: 280
    interfaces:
      - id: i0
        label: Loopback0
        mac_address: null
        type: loopback
      - id: i1
        label: GigabitEthernet0/0
        mac_address: null
        slot: 0
        type: physical
      - id: i2
        label: GigabitEthernet0/1
        mac_address: null
        slot: 1
        type: physical
      - id: i3
        label: GigabitEthernet0/2
        mac_address: null
        slot: 2
        type: physical
      - id: i4
        label: GigabitEthernet0/3
        mac_address: null
        slot: 3
        type: physical
  - boot_disk_size: null
    configuration:
      - name: ios_config.txt
        content: |-
          Building configuration...

          Current configuration : 2875 bytes
          !
          ! Last configuration change at 15:00:15 UTC Fri Nov 4 2022
          !
          version 15.2
          service timestamps debug datetime msec
          service timestamps log datetime msec
          no service password-encryption
          service compress-config
          !
          hostname SW1
          !
          boot-start-marker
          boot-end-marker
          !
          !
          !
          no aaa new-model
          !
          !
          !
          !
          !
          !
          !
          !
          ip cef
          no ipv6 cef
          !
          !
          !
          spanning-tree mode pvst
          spanning-tree extend system-id
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          interface GigabitEthernet0/0
           negotiation auto
          !
          interface GigabitEthernet0/1
           negotiation auto
          !
          interface GigabitEthernet0/2
           negotiation auto
          !
          interface GigabitEthernet0/3
           negotiation auto
          !
          ip forward-protocol nd
          !
          ip http server
          ip http secure-server
          !
          ip ssh server algorithm encryption aes128-ctr aes192-ctr aes256-ctr
          ip ssh client algorithm encryption aes128-ctr aes192-ctr aes256-ctr
          !
          !
          !
          !
          !
          !
          control-plane
          !
          banner exec ^C
          IOSv - Cisco Systems Confidential -

          Supplemental End User License Restrictions

          This IOSv software is provided AS-IS without warranty of any kind. Under no circumstances may this software be used separate from the Cisco Modeling Labs Software that this software was provided with, or deployed or used as part of a production environment.

          By using the software, you agree to abide by the terms and conditions of the Cisco End User License Agreement at http://www.cisco.com/go/eula. Unauthorized use or distribution of this software is expressly prohibited.
          ^C
          banner incoming ^C
          IOSv - Cisco Systems Confidential -

          Supplemental End User License Restrictions

          This IOSv software is provided AS-IS without warranty of any kind. Under no circumstances may this software be used separate from the Cisco Modeling Labs Software that this software was provided with, or deployed or used as part of a production environment.

          By using the software, you agree to abide by the terms and conditions of the Cisco End User License Agreement at http://www.cisco.com/go/eula. Unauthorized use or distribution of this software is expressly prohibited.
          ^C
          banner login ^C
          IOSv - Cisco Systems Confidential -

          Supplemental End User License Restrictions

          This IOSv software is provided AS-IS without warranty of any kind. Under no circumstances may this software be used separate from the Cisco Modeling Labs Software that this software was provided with, or deployed or used as part of a production environment.

          By using the software, you agree to abide by the terms and conditions of the Cisco End User License Agreement at http://www.cisco.com/go/eula. Unauthorized use or distribution of this software is expressly prohibited.
          ^C
          !
          line con 0
           exec-timeout 0 0
          line aux 0
          line vty 0 4
          !
          !
          end
    cpu_limit: 100
    cpus: null
    data_volume: null
    hide_links: false
    id: n1
    image_definition: null
    label: SW1
    node_definition: iosvl2
    parameters: {}
    ram: 768
    tags: []
    x: 760
    y: 280
    interfaces:
      - id: i0
        label: Loopback0
        mac_address: null
        type: loopback
      - id: i1
        label: GigabitEthernet0/0
        mac_address: null
        slot: 0
        type: physical
      - id: i2
        label: GigabitEthernet0/1
        mac_address: null
        slot: 1
        type: physical
      - id: i3
        label: GigabitEthernet0/2
        mac_address: null
        slot: 2
        type: physical
      - id: i4
        label: GigabitEthernet0/3
        mac_address: null
        slot: 3
        type: physical
  - boot_disk_size: null
    configuration:
      - name: ios_config.txt
        content: |-
          Building configuration...

          Current configuration : 2814 bytes
          !
          ! Last configuration change at 15:44:22 UTC Fri Nov 4 2022
          !
          version 15.2
          service timestamps debug datetime msec
          service timestamps log datetime msec
          no service password-encryption
          service compress-config
          !
          hostname SW2
          !
          boot-start-marker
          boot-end-marker
          !
          !
          !
          no aaa new-model
          !
          !
          !
          !
          !
          !
          !
          !
          ip cef
          no ipv6 cef
          !
          !
          !
          spanning-tree mode pvst
          spanning-tree extend system-id
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          !
          interface GigabitEthernet0/0
           negotiation auto
          !
          interface GigabitEthernet0/1
           negotiation auto
          !
          interface GigabitEthernet0/2
           negotiation auto
          !
          interface GigabitEthernet0/3
           negotiation auto
          !
          ip forward-protocol nd
          !
          ip http server
          ip http secure-server
          !
          ip ssh server algorithm encryption aes128-ctr aes192-ctr aes256-ctr
          ip ssh client algorithm encryption aes128-ctr aes192-ctr aes256-ctr
          !
          !
          !
          !
          !
          !
          control-plane
          !
          banner exec ^C
          IOSv - Cisco Systems Confidential -

          Supplemental End User License Restrictions

          This IOSv software is provided AS-IS without warranty of any kind. Under no circumstances may this software be used separate from the Cisco Modeling Labs Software that this software was provided with, or deployed or used as part of a production environment.

          By using the software, you agree to abide by the terms and conditions of the Cisco End User License Agreement at http://www.cisco.com/go/eula. Unauthorized use or distribution of this software is expressly prohibited.
          ^C
          banner incoming ^C
          IOSv - Cisco Systems Confidential -

          Supplemental End User License Restrictions

          This IOSv software is provided AS-IS without warranty of any kind. Under no circumstances may this software be used separate from the Cisco Modeling Labs Software that this software was provided with, or deployed or used as part of a production environment.

          By using the software, you agree to abide by the terms and conditions of the Cisco End User License Agreement at http://www.cisco.com/go/eula. Unauthorized use or distribution of this software is expressly prohibited.
          ^C
          banner login ^C
          IOSv - Cisco Systems Confidential -

          Supplemental End User License Restrictions

          This IOSv software is provided AS-IS without warranty of any kind. Under no circumstances may this software be used separate from the Cisco Modeling Labs Software that this software was provided with, or deployed or used as part of a production environment.

          By using the software, you agree to abide by the terms and conditions of the Cisco End User License Agreement at http://www.cisco.com/go/eula. Unauthorized use or distribution of this software is expressly prohibited.
          ^C
          !
          line con 0
           exec-timeout 0 0
          line aux 0
          line vty 0 4
          !
          !
          end
    cpu_limit: 100
    cpus: null
    data_volume: null
    hide_links: false
    id: n2
    image_definition: null
    label: SW2
    node_definition: iosvl2
    parameters: {}
    ram: 768
    tags: []
    x: 520
    y: 280
    interfaces:
      - id: i0
        label: Loopback0
        mac_address: null
        type: loopback
      - id: i1
        label: GigabitEthernet0/0
        mac_address: null
        slot: 0
        type: physical
      - id: i2
        label: GigabitEthernet0/1
        mac_address: null
        slot: 1
        type: physical
      - id: i3
        label: GigabitEthernet0/2
        mac_address: null
        slot: 2
        type: physical
      - id: i4
        label: GigabitEthernet0/3
        mac_address: null
        slot: 3
        type: physical
  - boot_disk_size: 16
    configuration:
      - name: node.cfg
        content: |-
          # this is a shell script which will be sourced at boot
          hostname PC-1
          # configurable user account
          ip addr add 192.168.10.10/24 dev eth0
          ip route add default via 192.168.10.1
          USERNAME=cisco
          PASSWORD=cisco
    cpu_limit: 100
    cpus: 1
    data_volume: 0
    hide_links: false
    id: n3
    image_definition: null
    label: PC-1
    node_definition: desktop
    parameters: {}
    ram: 512
    tags:
      - VLAN-10
    x: 760
    y: 80
    interfaces:
      - id: i0
        label: eth0
        mac_address: null
        slot: 0
        type: physical
  - boot_disk_size: 16
    configuration:
      - name: node.cfg
        content: |-
          # this is a shell script which will be sourced at boot
          hostname PC-2
          ip addr add 192.168.10.10/24 dev eth0
          ip route add default via 192.168.10.1
          # configurable user account
          USERNAME=cisco
          PASSWORD=cisco
    cpu_limit: 100
    cpus: 1
    data_volume: 0
    hide_links: false
    id: n4
    image_definition: null
    label: PC-2
    node_definition: desktop
    parameters: {}
    ram: 512
    tags:
      - VLAN-10
    x: 520
    y: 80
    interfaces:
      - id: i0
        label: eth0
        mac_address: null
        slot: 0
        type: physical
  - boot_disk_size: 16
    configuration:
      - name: iosxe_config.txt
        content: |-
          # this is a shell script which will be sourced at boot
          hostname server-1
          # configurable user account
          USERNAME=cisco
          PASSWORD=cisco
          ifconfig eth0 inet 192.168.20.2 netmask 255.255.255.0
          route add default gw 192.168.20.1
          # no password for tc user by default
          TC_PASSWORD=
    cpu_limit: 100
    cpus: 1
    data_volume: 0
    hide_links: false
    id: n5
    image_definition: null
    label: server-1
    node_definition: server
    parameters: {}
    ram: 128
    tags:
      - VLAN-20
    x: 760
    y: 440
    interfaces:
      - id: i0
        label: eth0
        mac_address: null
        slot: 0
        type: physical
  - boot_disk_size: 16
    configuration:
      - name: iosxe_config.txt
        content: |-
          # this is a shell script which will be sourced at boot
          hostname server-2
          # configurable user account
          USERNAME=cisco
          PASSWORD=cisco
          ifconfig eth0 inet 192.168.20.200 netmask 255.255.255.0
          route add default gw 192.168.20.1
          # no password for tc user by default
          TC_PASSWORD=
    cpu_limit: 100
    cpus: 1
    data_volume: 0
    hide_links: false
    id: n6
    image_definition: null
    label: server-2
    node_definition: server
    parameters: {}
    ram: 128
    tags:
      - VLAN-20
    x: 520
    y: 440
    interfaces:
      - id: i0
        label: eth0
        mac_address: null
        slot: 0
        type: physical
links:
  - id: l0
    n1: n1
    n2: n0
    i1: i1
    i2: i1
    conditioning: {}
    label: SW1-GigabitEthernet0/0<->R1-GigabitEthernet0/0
  - id: l1
    n1: n1
    n2: n3
    i1: i2
    i2: i0
    conditioning: {}
    label: SW1-GigabitEthernet0/1<->PC-1-eth0
  - id: l2
    n1: n1
    n2: n5
    i1: i3
    i2: i0
    conditioning: {}
    label: SW1-GigabitEthernet0/2<->server-1-eth0
  - id: l3
    n1: n1
    n2: n2
    i1: i4
    i2: i4
    conditioning: {}
    label: SW1-GigabitEthernet0/3<->SW2-GigabitEthernet0/3
  - id: l4
    n1: n2
    n2: n4
    i1: i2
    i2: i0
    conditioning: {}
    label: SW2-GigabitEthernet0/1<->PC-2-eth0
  - id: l5
    n1: n2
    n2: n6
    i1: i1
    i2: i0
    conditioning: {}
    label: SW2-GigabitEthernet0/0<->server-2-eth0
lab:
  description: |-
    This lab demonstrates how to configure Virtual LANs (VLANs) across multiple switches and how to use a router to enable communication between them. This common configuration is known as a "router-on-a-stick".

    Lab Objectives

    * Implement VLAN assignments on two switches.
    * Configure an 802.1q trunk link between two switches.
    * Configure an 802.1q trunk link between a switch and a router.
    * Configure sub-interfaces on the router to act as a gateway for each VLAN.
    * Verify end-to-end connectivity between hosts on different VLANs.
  notes: ''
  title: CCNA Demo VLAN Configuration
  version: 0.3.0
