annotations: []
smart_annotations:
  - tag: eigrp-1
    is_on: true
    padding: 35
    label: eigrp-1
    tag_offset_x: 0
    tag_offset_y: 0
    tag_size: 14
    group_distance: 400
    thickness: 1
    border_style: ''
    fill_color: '#A95FBE80'
    border_color: '#00000080'
    z_index: 1
nodes:
  - boot_disk_size: null
    configuration:
      - name: ios_config.txt
        content: |-
          hostname SW-1
          !
          interface GigabitEthernet0/1
          switchport mode access
          switchport access vlan 1
          !
          interface GigabitEthernet0/0
          switchport mode access
          switchport access vlan 1
          !
          end
          !
    cpu_limit: null
    cpus: null
    data_volume: null
    hide_links: false
    id: n0
    image_definition: null
    label: SW-1
    node_definition: iosvl2
    parameters: {}
    ram: null
    tags: []
    x: -320
    y: 40
    interfaces:
      - id: i0
        label: Loopback0
        mac_address: null
        type: loopback
      - id: i1
        label: GigabitEthernet0/0
        mac_address: null
        slot: 0
        type: physical
      - id: i2
        label: GigabitEthernet0/1
        mac_address: null
        slot: 1
        type: physical
      - id: i3
        label: GigabitEthernet0/2
        mac_address: null
        slot: 2
        type: physical
      - id: i4
        label: GigabitEthernet0/3
        mac_address: null
        slot: 3
        type: physical
  - boot_disk_size: null
    configuration:
      - name: ios_config.txt
        content: |2-

          hostname SW-2
          !
          interface GigabitEthernet0/1
          switchport mode access
          switchport access vlan 1
          !
          interface GigabitEthernet0/0
          switchport mode access
          switchport access vlan 1
          !
          end
          !
    cpu_limit: null
    cpus: null
    data_volume: null
    hide_links: false
    id: n1
    image_definition: null
    label: SW-2
    node_definition: iosvl2
    parameters: {}
    ram: null
    tags: []
    x: -320
    y: 240
    interfaces:
      - id: i0
        label: Loopback0
        mac_address: null
        type: loopback
      - id: i1
        label: GigabitEthernet0/0
        mac_address: null
        slot: 0
        type: physical
      - id: i2
        label: GigabitEthernet0/1
        mac_address: null
        slot: 1
        type: physical
      - id: i3
        label: GigabitEthernet0/2
        mac_address: null
        slot: 2
        type: physical
      - id: i4
        label: GigabitEthernet0/3
        mac_address: null
        slot: 3
        type: physical
  - boot_disk_size: null
    configuration:
      - name: ios_config.txt
        content: |
          hostname SW-3
          !
          interface GigabitEthernet0/1
          switchport mode access
          switchport access vlan 1
          !
          interface GigabitEthernet0/0
          switchport mode access
          switchport access vlan 1
          !
          end
          !
    cpu_limit: null
    cpus: null
    data_volume: null
    hide_links: false
    id: n2
    image_definition: null
    label: SW-3
    node_definition: iosvl2
    parameters: {}
    ram: null
    tags: []
    x: 160
    y: 160
    interfaces:
      - id: i0
        label: Loopback0
        mac_address: null
        type: loopback
      - id: i1
        label: GigabitEthernet0/0
        mac_address: null
        slot: 0
        type: physical
      - id: i2
        label: GigabitEthernet0/1
        mac_address: null
        slot: 1
        type: physical
      - id: i3
        label: GigabitEthernet0/2
        mac_address: null
        slot: 2
        type: physical
      - id: i4
        label: GigabitEthernet0/3
        mac_address: null
        slot: 3
        type: physical
  - boot_disk_size: null
    configuration:
      - name: ios_config.txt
        content: |2-

          hostname R-1
          !
          interface Loopback0
          ip address 1.1.1.1 255.255.255.255
          !
          interface GigabitEthernet0/0
          ip address 10.0.1.1 255.255.255.0
          no shutdown
          !
          interface GigabitEthernet0/1
          ip address 10.0.4.1 255.255.255.0
          no shutdown
          !
          interface GigabitEthernet0/2
          ip address 10.0.5.1 255.255.255.0
          no shutdown
          !
          router eigrp 1
          network 10.0.0.0
          !
          end
          !
    cpu_limit: null
    cpus: null
    data_volume: null
    hide_links: false
    id: n3
    image_definition: null
    label: R-1
    node_definition: iosv
    parameters: {}
    ram: null
    tags:
      - eigrp-1
    x: -160
    y: 40
    interfaces:
      - id: i0
        label: Loopback0
        mac_address: null
        type: loopback
      - id: i1
        label: GigabitEthernet0/0
        mac_address: null
        slot: 0
        type: physical
      - id: i2
        label: GigabitEthernet0/1
        mac_address: null
        slot: 1
        type: physical
      - id: i3
        label: GigabitEthernet0/2
        mac_address: null
        slot: 2
        type: physical
      - id: i4
        label: GigabitEthernet0/3
        mac_address: null
        slot: 3
        type: physical
  - boot_disk_size: null
    configuration:
      - name: ios_config.txt
        content: |2-

          interface Loopback0
          ip address 2.2.2.2 255.255.255.255
          !
          interface GigabitEthernet0/0
          ip address 10.0.2.1 255.255.255.0
          no shutdown
          !
          interface GigabitEthernet0/1
          ip address 10.0.6.1 255.255.255.0
          no shutdown
          !
          interface GigabitEthernet0/2
          ip address 10.0.5.2 255.255.255.0
          no shutdown
          !
          router eigrp 1
          network 10.0.0.0
          !
          end
          !
    cpu_limit: null
    cpus: null
    data_volume: null
    hide_links: false
    id: n4
    image_definition: null
    label: R-2
    node_definition: iosv
    parameters: {}
    ram: null
    tags:
      - eigrp-1
    x: -160
    y: 240
    interfaces:
      - id: i0
        label: Loopback0
        mac_address: null
        type: loopback
      - id: i1
        label: GigabitEthernet0/0
        mac_address: null
        slot: 0
        type: physical
      - id: i2
        label: GigabitEthernet0/1
        mac_address: null
        slot: 1
        type: physical
      - id: i3
        label: GigabitEthernet0/2
        mac_address: null
        slot: 2
        type: physical
      - id: i4
        label: GigabitEthernet0/3
        mac_address: null
        slot: 3
        type: physical
  - boot_disk_size: null
    configuration:
      - name: ios_config.txt
        content: |2-

          hostname R-3
          !
          interface Loopback0
          ip address 3.3.3.3 255.255.255.255
          !
          interface GigabitEthernet0/0
          ip address 10.0.3.1 255.255.255.0
          no shutdown
          !
          interface GigabitEthernet0/1
          ip address 10.0.4.2 255.255.255.0
          no shutdown
          !
          interface GigabitEthernet0/2
          ip address 10.0.6.2 255.255.255.0
          no shutdown
          !
          router eigrp 1
          network 10.0.0.0
          !
          end
          !
    cpu_limit: null
    cpus: null
    data_volume: null
    hide_links: false
    id: n5
    image_definition: null
    label: R-3
    node_definition: iosv
    parameters: {}
    ram: null
    tags:
      - eigrp-1
    x: 0
    y: 160
    interfaces:
      - id: i0
        label: Loopback0
        mac_address: null
        type: loopback
      - id: i1
        label: GigabitEthernet0/0
        mac_address: null
        slot: 0
        type: physical
      - id: i2
        label: GigabitEthernet0/1
        mac_address: null
        slot: 1
        type: physical
      - id: i3
        label: GigabitEthernet0/2
        mac_address: null
        slot: 2
        type: physical
      - id: i4
        label: GigabitEthernet0/3
        mac_address: null
        slot: 3
        type: physical
  - boot_disk_size: null
    configuration:
      - name: node.cfg
        content: |+
          # this is a shell script which will be sourced at boot
          hostname PC-1
          # configurable user account
          USERNAME=cisco
          PASSWORD=cisco

          ip address add 10.0.1.10/24 dev eth0
          ip link set dev eth0 up
          ip route add default via 10.0.1.1

    cpu_limit: null
    cpus: null
    data_volume: null
    hide_links: false
    id: n6
    image_definition: null
    label: PC-1
    node_definition: alpine
    parameters: {}
    ram: null
    tags: []
    x: -480
    y: 40
    interfaces:
      - id: i0
        label: eth0
        mac_address: null
        slot: 0
        type: physical
  - boot_disk_size: null
    configuration:
      - name: node.cfg
        content: |-
          # this is a shell script which will be sourced at boot
          hostname PC-2
          # configurable user account
          USERNAME=cisco
          PASSWORD=cisco

          ip address add 10.0.2.10/24 dev eth0
          ip link set dev eth0 up
          ip route add default via 10.0.2.1
    cpu_limit: null
    cpus: null
    data_volume: null
    hide_links: false
    id: n7
    image_definition: null
    label: PC-2
    node_definition: alpine
    parameters: {}
    ram: null
    tags: []
    x: -480
    y: 240
    interfaces:
      - id: i0
        label: eth0
        mac_address: null
        slot: 0
        type: physical
  - boot_disk_size: null
    configuration:
      - name: node.cfg
        content: |-
          # this is a shell script which will be sourced at boot
          hostname PC-3
          # configurable user account
          USERNAME=cisco
          PASSWORD=cisco
    cpu_limit: null
    cpus: null
    data_volume: null
    hide_links: false
    id: n8
    image_definition: null
    label: PC-3
    node_definition: alpine
    parameters: {}
    ram: null
    tags: []
    x: 360
    y: 160
    interfaces:
      - id: i0
        label: eth0
        mac_address: null
        slot: 0
        type: physical
links:
  - id: l0
    n1: n0
    n2: n3
    i1: i1
    i2: i1
    conditioning: {}
    label: SW-1-GigabitEthernet0/0<->R-1-GigabitEthernet0/0
  - id: l1
    n1: n1
    n2: n4
    i1: i1
    i2: i1
    conditioning: {}
    label: SW-2-GigabitEthernet0/0<->R-2-GigabitEthernet0/0
  - id: l2
    n1: n5
    n2: n2
    i1: i1
    i2: i1
    conditioning: {}
    label: R-3-GigabitEthernet0/0<->SW-3-GigabitEthernet0/0
  - id: l3
    n1: n3
    n2: n5
    i1: i2
    i2: i2
    conditioning: {}
    label: R-1-GigabitEthernet0/1<->R-3-GigabitEthernet0/1
  - id: l4
    n1: n3
    n2: n4
    i1: i3
    i2: i3
    conditioning: {}
    label: R-1-GigabitEthernet0/2<->R-2-GigabitEthernet0/2
  - id: l5
    n1: n5
    n2: n4
    i1: i3
    i2: i2
    conditioning: {}
    label: R-3-GigabitEthernet0/2<->R-2-GigabitEthernet0/1
  - id: l6
    n1: n6
    n2: n0
    i1: i0
    i2: i2
    conditioning: {}
    label: PC-1-eth0<->SW-1-GigabitEthernet0/1
  - id: l7
    n1: n7
    n2: n1
    i1: i0
    i2: i2
    conditioning: {}
    label: PC-2-eth0<->SW-2-GigabitEthernet0/1
  - id: l8
    n1: n8
    n2: n2
    i1: i0
    i2: i2
    conditioning: {}
    label: PC-3-eth0<->SW-3-GigabitEthernet0/1
lab:
  description: In this lab, you'll enable IPv6 on a network that's already running
    IPv4. You will start by studying the network's layout. Then, you'll manually set
    up IPv6 addresses on two routers. After that, you'll configure two end devices
    to automatically get their IPv6 addresses. Finally, you'll test to make sure everything
    can communicate using IPv6.
  notes: |-
    # CML IPv6 Configuration Lab

    ## **Objective**

    This lab guide will walk you through the process of configuring basic IPv6 connectivity on your existing CML topology. You will first verify the initial IPv4 setup, then enable IPv6 routing, configure IPv6 addresses on routers, and finally verify that the end devices (all Alpine Linux) have automatically received IPv6 addresses using Stateless Address Autoconfiguration (SLAAC).

    ## **Lab Topology**

    The lab uses the following topology:

    * **Routers:** R-1, R-2, R-3
    * **Switches:** SW-1, SW-2, SW-3
    * **End Devices:** PC-1 (Alpine), PC-2 (Alpine), PC-3 (Alpine)

    ## **IPv4 Addressing Plan**

    | Device | Interface | IPv4 Address | Default Gateway |
    | :--- | :--- | :--- | :--- |
    | R-1 | Gi0/0 | 10.0.1.1/24 | N/A |
    | R-1 | Gi0/1 | 10.0.4.1/24 | N/A |
    | R-1 | Gi0/2 | 10.0.5.1/24 | N/A |
    | R-2 | Gi0/0 | 10.0.2.1/24 | N/A |
    | R-2 | Gi0/1 | 10.0.6.1/24 | N/A |
    | R-2 | Gi0/2 | 10.0.5.2/24 | N/A |
    | R-3 | Gi0/0 | 10.0.3.1/24 | N/A |
    | R-3 | Gi0/1 | 10.0.4.2/24 | N/A |
    | R-3 | Gi0/2 | 10.0.6.2/24 | N/A |
    | PC-1 | eth0 | 10.0.1.10/24 | 10.0.1.1 |
    | PC-2 | eth0 | 10.0.2.10/24 | 10.0.2.1 |
    | PC-3| eth0 | 10.0.3.10/24 | 10.0.3.1 |

    ## **IPv6 Addressing Plan**

    | Device | Interface | IPv6 Address | Default Gateway |
    | :--- | :--- | :--- | :--- |
    | R-1 | Gi0/0 | `2001:CAFE:1::1/64` | N/A |
    | R-1 | Gi0/1 | `2001:CAFE:4::1/64` | N/A |
    | R-1 | Gi0/2 | `2001:CAFE:5::1/64` | N/A |
    | R-2 | Gi0/0 | `2001:CAFE:2::1/64` | N/A |
    | R-2 | Gi0/1 | `2001:CAFE:6::1/64` | N/A |
    | R-2 | Gi0/2 | `2001:CAFE:5::2/64` | N/A |
    | R-3 | Gi0/0 | `2001:CAFE:3::1/64` | N/A |
    | R-3 | Gi0/1 | `2001:CAFE:4::2/64` | N/A |
    | R-3 | Gi0/2 | `2001:CAFE:6::2/64` | N/A |
    | PC-1 | eth0 | SLAAC | Link-Local of R-1 Gi0/0 |
    | PC-2 | eth0 | SLAAC | Link-Local of R-2 Gi0/0 |
    | PC-3| eth0 | SLAAC | Link-Local of R-3 Gi0/0 |

    ---

    ### **Part 1: Verify Initial IPv4 Connectivity**

    Before configuring IPv6, ensure that the existing IPv4 network is fully operational. The initial configuration for the Linux hosts should have already set their IPv4 address and default gateway.

    #### **Step 1: Test connectivity from PC-1 to PC-3**

    Log into the console of PC-1 (Alpine Linux) and ping the IPv4 address of PC-3.
    ```
    # From the PC-1 console
    ping 10.0.3.10
    ```
    *The ping should be successful, indicating that EIGRP is routing traffic correctly.*

    #### **Step 2: Test connectivity from PC-2 to PC-3**

    Next, log into the console of PC-2 (Alpine Linux) and ping the IPv4 address of PC-3.
    ```
    # From the PC-2 console
    ping 10.0.3.10
    ```
    *This ping should also be successful.*

    ---

    ### **Part 2: Configure IPv6 on Routers**

    #### **Step 1: Enable IPv6 Routing on R-1**

    On a Cisco router, IPv6 routing is disabled by default. Use the `ipv6 unicast-routing` command to enable it. This command allows the router to forward IPv6 packets and send Router Advertisements (RAs) for SLAAC.

    ```
    ! On R-1
    configure terminal
     ipv6 unicast-routing
    ```

    #### **Step 2: Configure IPv6 Addresses on R-1 Interfaces**

    Assign the IPv6 addresses from the addressing table to the interfaces on R-1.

    ```
    ! On R-1
    interface GigabitEthernet0/0
     ipv6 address 2001:CAFE:1::1/64
     no shutdown
    !
    interface GigabitEthernet0/1
     ipv6 address 2001:CAFE:4::1/64
     no shutdown
    !
    interface GigabitEthernet0/2
     ipv6 address 2001:CAFE:5::1/64
     no shutdown
    ```

    #### **Step 3: Enable IPv6 Routing and Configure Addresses on R-2**

    Repeat the process for R-2.

    ```
    ! On R-2
    configure terminal
     ipv6 unicast-routing
    !
    interface GigabitEthernet0/0
     ipv6 address 2001:CAFE:2::1/64
     no shutdown
    !
    interface GigabitEthernet0/1
     ipv6 address 2001:CAFE:6::1/64
     no shutdown
    !
    interface GigabitEthernet0/2
     ipv6 address 2001:CAFE:5::2/64
     no shutdown
    ```

    #### **Step 4: Enable IPv6 Routing and Configure Addresses on R-3**

    Finally, configure R-3.

    ```
    ! On R-3
    configure terminal
     ipv6 unicast-routing
    !
    interface GigabitEthernet0/0
     ipv6 address 2001:CAFE:3::1/64
     no shutdown
    !
    interface GigabitEthernet0/1
     ipv6 address 2001:CAFE:4::2/64
     no shutdown
    !
    interface GigabitEthernet0/2
     ipv6 address 2001:CAFE:6::2/64
     no shutdown
    ```

    #### **Step 5: Verify Direct Connectivity**

    From R-1, you should now be able to ping the directly connected IPv6 interfaces of R-2 and R-3.

    ```
    ! On R-1
    do ping 2001:CAFE:5::2  ! Pinging R-2
    do ping 2001:CAFE:4::2  ! Pinging R-3
    ```
    *You should see a 100% success rate for both pings.*

    ---

    ### **Part 3: Verify SLAAC on End Devices**

    With IPv6 enabled on the routers, they automatically send Router Advertisement (RA) messages. The Linux hosts will listen for these RAs and use them to configure their own IPv6 addresses and default gateways.

    #### **Step 1: Verify IPv6 Configuration on PC-1 (Alpine Linux)**

    Log into the console of PC-1 and verify that it has received an IPv6 address and a default route via SLAAC.

    ```
    # From the PC-1 console
    ip -6 addr show
    ip -6 route show
    ```
    *You should see a global unicast address starting with `2001:CAFE:1::/64` and a default route (`default via fe80...`) pointing to the link-local address of R-1's Gi0/0 interface.*

    #### **Step 2: Verify Connectivity from PC-1**

    From the PC-1 console, ping the IPv6 address of its gateway (R-1).

    ```
    # From the PC-1 console
    ping 2001:CAFE:1::1
    ```
    *This ping should be successful.*

    #### **Step 3: Verify IPv6 Configuration on PC-3 (Alpine Linux)**

    Log into the console of PC-3 and verify that it has received an IPv6 address and a default route via SLAAC.

    ```
    # From the PC-3 console
    ip -6 addr show
    ip -6 route show
    ```
    *In the output, you should now see a global unicast address starting with `2001:CAFE:3::/64` and a default route (`default via fe80...`) pointing to the link-local address of R-3's Gi0/0 interface.*

    #### **Step 4: Verify Connectivity from PC-3**

    From the PC-3 console, use the `ping` command to test connectivity to its gateway (R-3).

    ```
    # From the PC-3 console
    ping 2001:CAFE:3::1
    ```
    *This ping should be successful.*

    You have now configured and verified basic IPv6 connectivity in your lab! You can perform the same verification steps on PC-2 to ensure it is also working correctly.
  title: Configure Basic IPv6 Connectivity
  version: 0.3.0
